services:
  postgres:
    image: postgres:15-alpine
    container_name: newsem-postgres
    environment:
      POSTGRES_DB: newsem_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - newsem_postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  newsem_postgres_data:
