server.port=${TLS_PORT:8443}
server.ssl.enabled=true
server.ssl.key-store=${TLS_KEYSTORE_PATH:./.secrets/tls/server-keystore.p12}
server.ssl.key-store-type=PKCS12
server.ssl.key-store-password=${TLS_KEYSTORE_PASSWORD}
server.ssl.key-alias=${TLS_KEY_ALIAS:service-tls}
